version: '3.3'
services:
    node:
        context: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
        container_name: spotapi-token
        image: node:latest
        command: node app.js